# genai
spring.ai.google.genai.api-key=${GEMINI_API_KEY:no-key}
# https://aistudio.google.com/prompts/new_chat?model=gemini-3.5-flash-lite
spring.ai.google.genai.chat.model=gemini-3.5-flash-lite

# embeddings
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY:no-key}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.dimensions=1536
# 3072, 1536, 768 -> dynamic dimensions -> pgvector 2000
# pgvector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1536
#spring.ai.vectorstore.pgvector.index-type=HNSW
#spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE